### ISSUE TITLE
Error: missing 1 required positional argument: 'loop' 

### ISSUE THREAD

**Issue by shraddhaamohan** [samyak-jain/AgoraPython#1]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-89680e863cb6> in <module>
      1 from agora_community_sdk import AgoraRTC
      2 import cv2
----> 3 client = AgoraRTC("fd6db7ee116b48039e92d7273b7249fe")
      4 client.join_channel("demoChannel1")
      5 

TypeError: __init__() missing 1 required positional argument: 'loop'

```
Tried both on jupyter notebook and cmd

**Comment by samyak-jain** [comment]
There was an issue with the code sample. You need to call the create_watcher method. It's now updated. Refer the updated Readme. Let me know if the issue is fixed

**Comment by srinathvrao** [comment]
```
Traceback (most recent call last):
  File "ago.py", line 3, in <module>
    client.join_channel("demoChannel1")
  File "/home/srinath/miniconda3/lib/python3.7/site-packages/agora_community_sdk/agora.py", line 166, in join_channel
    run_async_code(self.creator, self.loop)
  File "/home/srinath/miniconda3/lib/python3.7/site-packages/agora_community_sdk/agora.py", line 21, in run_async_code
    return loop.run_until_complete(function())
  File "/home/srinath/miniconda3/lib/python3.7/site-packages/nest_asyncio.py", line 63, in run_until_complete
    return self._run_until_complete_orig(future)
  File "/home/srinath/miniconda3/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/srinath/miniconda3/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/srinath/miniconda3/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/home/srinath/miniconda3/lib/python3.7/site-packages/agora_community_sdk/agora.py", line 159, in creator
    await self.page.waitForSelector("video.playing")
  File "/home/srinath/miniconda3/lib/python3.7/site-packages/pyppeteer/frame_manager.py", line 834, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "video.playing" failed: timeout 30000ms exceeds.

```
error in client.join_channel()

**Comment by samyak-jain** [comment]
Readme updated with instructions on how to fix the issue.
